import { Product, Sale, User, StockAdjustment } from '@/types';

export const mockProducts: Product[] = [
  // Fixed-price products
  {
    id: 'P001',
    name: 'Hammer - Claw 16oz',
    category: 'Tools',
    supplier: 'Stanley Tools',
    costPrice: 15.00,
    pricingType: 'fixed',
    sellingPrice: 25.00,
    quantity: 50,
    reorderLevel: 10,
    brand: 'Stanley',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P002',
    name: 'Screwdriver Set - Phillips',
    category: 'Tools',
    supplier: 'Craftsman',
    costPrice: 12.00,
    pricingType: 'fixed',
    sellingPrice: 20.00,
    quantity: 30,
    reorderLevel: 5,
    brand: 'Craftsman',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P003',
    name: 'Wood Screws 2" - Pack of 100',
    category: 'Fasteners',
    supplier: 'FastCo',
    costPrice: 8.00,
    pricingType: 'fixed',
    sellingPrice: 15.00,
    quantity: 200,
    reorderLevel: 25,
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P004',
    name: 'Paint - Interior White 1 Gallon',
    category: 'Paint',
    supplier: 'Sherwin Williams',
    costPrice: 25.00,
    pricingType: 'fixed',
    sellingPrice: 45.00,
    quantity: 15,
    reorderLevel: 5,
    brand: 'Sherwin Williams',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P005',
    name: 'Drill Bits Set - HSS',
    category: 'Tools',
    supplier: 'DeWalt',
    costPrice: 20.00,
    pricingType: 'fixed',
    sellingPrice: 35.00,
    quantity: 25,
    reorderLevel: 8,
    brand: 'DeWalt',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  
  // Weight-based products
  {
    id: 'P006',
    name: 'Steel Nails - Common',
    category: 'Fasteners',
    supplier: 'MetalCorp',
    costPrice: 6.00,
    pricingType: 'weight-based',
    pricePerKg: 12.50,
    totalWeightKg: 45.5,
    minWeightKg: 10.0,
    brand: 'MetalCorp',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P007',
    name: 'Concrete Mix',
    category: 'Building Materials',
    supplier: 'BuildSupply',
    costPrice: 1.20,
    pricingType: 'weight-based',
    pricePerKg: 2.50,
    totalWeightKg: 150.0,
    minWeightKg: 25.0,
    brand: 'QuikCrete',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P008',
    name: 'Gravel - Fine',
    category: 'Building Materials',
    supplier: 'RockCorp',
    costPrice: 0.80,
    pricingType: 'weight-based',
    pricePerKg: 1.75,
    totalWeightKg: 200.0,
    minWeightKg: 50.0,
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P009',
    name: 'Measuring Tape 25ft',
    category: 'Tools',
    supplier: 'Stanley Tools Inc.',
    costPrice: 6.50,
    pricingType: 'fixed',
    sellingPrice: 11.99,
    quantity: 42,
    reorderLevel: 12,
    brand: 'Stanley',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P010',
    name: 'Steel Rebar - 12mm',
    category: 'Building Materials',
    supplier: 'SteelWorks',
    costPrice: 4.50,
    pricingType: 'weight-based',
    pricePerKg: 8.75,
    totalWeightKg: 85.0,
    minWeightKg: 20.0,
    brand: 'SteelWorks',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P011',
    name: 'Sandpaper Assorted (10pc)',
    category: 'Abrasives',
    supplier: 'Art & Paint Supply',
    costPrice: 4.50,
    pricingType: 'fixed',
    sellingPrice: 7.99,
    quantity: 85,
    reorderLevel: 20,
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P012',
    name: 'Copper Wire - 14 AWG',
    category: 'Electrical',
    supplier: 'ElectricCorp',
    costPrice: 8.50,
    pricingType: 'weight-based',
    pricePerKg: 18.75,
    totalWeightKg: 25.0,
    minWeightKg: 5.0,
    brand: 'ElectricCorp',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P013',
    name: 'Aluminum Sheets - 2mm',
    category: 'Building Materials',
    supplier: 'MetalWorks',
    costPrice: 12.00,
    pricingType: 'weight-based',
    pricePerKg: 25.50,
    totalWeightKg: 15.5,
    minWeightKg: 3.0,
    brand: 'MetalWorks',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P014',
    name: 'Pliers Set (3pc)',
    category: 'Tools',
    supplier: 'Stanley Tools Inc.',
    costPrice: 18.00,
    pricingType: 'fixed',
    sellingPrice: 29.99,
    quantity: 6,
    reorderLevel: 10,
    brand: 'Stanley',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P015',
    name: 'Roofing Nails - Galvanized',
    category: 'Fasteners',
    supplier: 'FastCo',
    costPrice: 4.25,
    pricingType: 'weight-based',
    pricePerKg: 9.50,
    totalWeightKg: 75.0,
    minWeightKg: 15.0,
    brand: 'FastCo',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P016',
    name: 'Safety Goggles',
    category: 'Safety',
    supplier: '3M Safety Products',
    costPrice: 4.00,
    pricingType: 'fixed',
    sellingPrice: 8.99,
    quantity: 35,
    reorderLevel: 15,
    brand: '3M',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P017',
    name: 'Crushed Stone - Medium',
    category: 'Building Materials',
    supplier: 'RockCorp',
    costPrice: 0.65,
    pricingType: 'weight-based',
    pricePerKg: 1.45,
    totalWeightKg: 500.0,
    minWeightKg: 100.0,
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P018',
    name: 'Welding Rod - 3.2mm',
    category: 'Welding',
    supplier: 'WeldPro',
    costPrice: 15.00,
    pricingType: 'weight-based',
    pricePerKg: 32.50,
    totalWeightKg: 8.5,
    minWeightKg: 2.0,
    brand: 'WeldPro',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P019',
    name: 'Mortar Mix',
    category: 'Building Materials',
    supplier: 'BuildSupply',
    costPrice: 2.10,
    pricingType: 'weight-based',
    pricePerKg: 4.25,
    totalWeightKg: 120.0,
    minWeightKg: 25.0,
    brand: 'MortarPro',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: 'P020',
    name: 'Chain Link - Galvanized',
    category: 'Fencing',
    supplier: 'FenceCorp',
    costPrice: 6.75,
    pricingType: 'weight-based',
    pricePerKg: 14.50,
    totalWeightKg: 35.0,
    minWeightKg: 10.0,
    brand: 'FenceCorp',
    lastUpdated: '2024-01-15T10:30:00Z',
  },
];

export const mockSales: Sale[] = [
  {
    id: 'S001',
    items: [
      { productId: 'P001', productName: 'Hammer - Claw Type', quantity: 2, unitPrice: 24.99, subtotal: 49.98 },
      { productId: 'P003', productName: 'Wood Screws 2" (100pc)', quantity: 1, unitPrice: 12.99, subtotal: 12.99 },
    ],
    subtotal: 62.97,
    discount: 0,
    total: 62.97,
    paymentMethod: 'cash',
    date: new Date().toISOString(),
    processedBy: 'John Doe',
  },
  {
    id: 'S002',
    items: [
      { productId: 'P006', productName: 'Power Drill - Cordless', quantity: 1, unitPrice: 149.99, subtotal: 149.99 },
    ],
    subtotal: 149.99,
    discount: 10,
    total: 139.99,
    paymentMethod: 'card',
    date: new Date(Date.now() - 86400000).toISOString(),
    processedBy: 'Jane Smith',
  },
];

export const mockUsers: User[] = [
  {
    id: 'U001',
    name: 'John Doe',
    email: 'john.doe@hardware.com',
    role: 'admin',
    active: true,
  },
  {
    id: 'U002',
    name: 'Jane Smith',
    email: 'jane.smith@hardware.com',
    role: 'cashier',
    active: true,
  },
  {
    id: 'U003',
    name: 'Bob Manager',
    email: 'bob.manager@hardware.com',
    role: 'manager',
    active: true,
  },
];

export const mockStockAdjustments: StockAdjustment[] = [
  {
    id: 'A001',
    productId: 'P004',
    productName: 'Nails 3" (500g)',
    quantityChange: -5,
    reason: 'Damaged during shipment',
    adjustedBy: 'John Doe',
    date: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const categories = ['Tools', 'Fasteners', 'Paint', 'Safety', 'Abrasives', 'Building Materials', 'Electrical', 'Welding', 'Fencing'];
export const suppliers = ['Stanley Tools Inc.', 'DeWalt Supplies', 'Bolt & Screw Co.', 'Art & Paint Supply', '3M Safety Products'];
